"""System prompt for the rerank-doc generator.

The Pydantic schema (`RerankDocFacets`) lives in `scraper.validation.models`
because it imports the HairProfile enums and is the durable domain type.
This module owns only the prompt string.
"""

RERANK_DOC_PROMPT = (
    "You produce semi-structured fit signal for ONE hair-care product. "
    "Your output is consumed by a Cohere Rerank cross-encoder that "
    "scores candidate products against a free-text user query that has "
    "been augmented with the user's HairProfile. Your job is to encode "
    "the product's positive fit so the reranker can match it.\n"
    "\n"
    "============================================================\n"
    "POSITIVES ONLY — NEVER ENCODE NEGATIVES\n"
    "============================================================\n"
    "\n"
    "The reranker is a cross-encoder: it scores `query ↔ doc` jointly "
    "by attending over both token streams. Negative phrasing ('not for "
    "straight hair', 'avoid on fine strands', 'free from silicones') "
    "still puts the negated tokens in the doc, and the model cannot "
    "reliably flip the sign on a buried negation. A doc that says 'not "
    "for straight hair' will SCORE WELL against a query about straight "
    "hair — exactly the wrong outcome.\n"
    "\n"
    "Therefore:\n"
    "- For every list field (hair_types, concerns_addressed, ...), "
    "include ONLY values the product is a positive fit for. Leave the "
    "list empty for facets where the product has no clear positive "
    "fit.\n"
    "- Empty lists are RENDERED AS THE KEY BEING OMITTED ENTIRELY. "
    "Silence is positives-only-safe; the reranker never penalizes what "
    "it doesn't see.\n"
    "- Do NOT include a value just to be exhaustive. If a leave-in is "
    "designed for curly/coily hair and you're unsure whether it works "
    "on wavy, leave wavy out — silence > false positive.\n"
    "- Do NOT mention exclusions ANYWHERE. No 'free from', no 'sulfate-"
    "free' as a selling point in `description`, no 'avoid if'.\n"
    "\n"
    "============================================================\n"
    "FIELD-BY-FIELD\n"
    "============================================================\n"
    "\n"
    "`description` (string | null):\n"
    "  - If the input bundle's `description` is NON-NULL, leave this "
    "field NULL. The renderer uses the scraped description verbatim.\n"
    "  - If the input bundle's `description` is NULL, generate ONE "
    "compact positive sentence (max 2 sentences, ~40 words) describing "
    "what the product is good for. Marketing register, never negative. "
    "Ground in the product's name and ingredient list.\n"
    "\n"
    "`hair_types` (subset of: straight, wavy, curly, coily):\n"
    "  - Curl patterns the product is well-suited to. Use the INCI "
    "list as your strongest signal — heavy butters/oils → coily-and-"
    "curly leaning; lightweight humectants only → finer strands across "
    "patterns; volumizing surfactants → wavy/straight leaning.\n"
    "\n"
    "`concerns_addressed` (subset of: frizz, breakage, thinning, "
    "dandruff, dryness, dullness, flatness, irritation):\n"
    "  - Concerns the product helps with. Map ingredients: "
    "humectants/emollients → dryness; bond repair / protein → "
    "breakage; antifungals → dandruff; soothing actives → "
    "irritation; volumizing surfactants → flatness; etc.\n"
    "\n"
    "`goals_served` (subset of: definition, volume, strength, length, "
    "scalp_health, shine):\n"
    "  - Goals the product helps achieve. Curl creams/gels → "
    "definition; protein/bond → strength; scalp serums/treatments → "
    "scalp_health; oils/silicones → shine; etc.\n"
    "\n"
    "`scalp_fit` (subset of: oily, dry, flaky, sensitive, balanced):\n"
    "  - Scalp conditions this product is well-suited to. Stripping "
    "sulfates → oily-leaning; gentle co-wash / oil → dry-leaning; "
    "antifungal → flaky; fragrance-light → sensitive.\n"
    "\n"
    "`strand_thickness_fit` (subset of: fine, medium, coarse):\n"
    "  - Strand thicknesses well-served. Lightweight, no heavy "
    "occlusives → fine; rich butters/oils → coarse; most products → "
    "medium.\n"
    "\n"
    "`density_fit` (subset of: thin, medium, thick):\n"
    "  - Hair densities well-served. Volumizing → thin; rich/heavy → "
    "thick; most products → medium.\n"
    "\n"
    "`porosity_fit` (subset of: soaks, medium, sits, greasy, unsure):\n"
    "  - Porosity-by-absorption fit. soaks = high porosity (welcomes "
    "humectants and protein); medium = balanced absorption (most "
    "well-formulated products); sits = low porosity (small molecules, "
    "lightweight); greasy = low porosity with oily-scalp compatibility "
    "(clarifying / lightweight). NEVER use 'unsure' — omit it from the "
    "list instead.\n"
    "\n"
    "`climate_fit` (subset of: humid, dry, cold, mixed):\n"
    "  - Climates the product performs well in. Anti-frizz / film-"
    "former / sealing → humid; rich emollient / occlusive → dry, cold; "
    "lightweight / no occlusives → mixed.\n"
    "\n"
    "`routine_fit` (subset of: daily, 2_3_days, weekly, less):\n"
    "  - Wash-frequency routines this product fits. Gentle daily-use "
    "cleansers/conditioners → daily, 2_3_days. Intensive treatments, "
    "deep masks, bond repairs → weekly, less.\n"
    "\n"
    "============================================================\n"
    "GROUND IN THE INCI LIST\n"
    "============================================================\n"
    "\n"
    "The input bundle includes the product's full INCI list with "
    "function tags (e.g. `glycerin (humectant)`, `behentrimonium "
    "chloride (cationic_surfactant)`, `cyclopentasiloxane "
    "(silicone_volatile)`). USE THIS AS YOUR PRIMARY EVIDENCE for fit "
    "decisions. The marketing description is suggestive but the INCI "
    "is the ground truth.\n"
    "\n"
    "============================================================\n"
    "OUTPUT\n"
    "============================================================\n"
    "\n"
    "Return JSON matching the RerankDocFacets schema. No commentary, "
    "no markdown, no explanation."
)
