-- =============================================================================
-- Brand-pool expansion (2026-04-27): 124 new brands
-- 
-- Driven by the 2026-04-27 diversity audit (sleek/straight under-
-- representation, dandruff/thinning supply gaps, K/J-beauty thinness,
-- indie textured long-tail). Initially attempted via 5 + 3 + 3 firecrawl
-- agent runs at credit caps 300/800/1500 — every run hit the agent's
-- internal planning-step ceiling regardless of cap. Pivoted to curated
-- candidates run through the same dedup + URL-validation pipeline as
-- the agent output would have been (slug/name/eTLD+1 dedup against
-- existing brands; curl HEAD/GET validation; URL-invalid rows dropped).
-- 
-- Idempotent on slug. Refreshes name/website_url/tier on conflict.
-- Source breakdown:
--   brands-A-western-pro.json: 37
--   brands-B-scalp.json: 40
--   brands-C-asia-indie.json: 47
-- =============================================================================

insert into brands (slug, name, website_url, tier) values
  ('africas-best', 'Africa''s Best', 'https://www.africasbest.com', 'everyday'),
  ('ahc', 'AHC', 'https://www.ahcbeauty.com', 'luxury'),
  ('alfaparf-milano', 'Alfaparf Milano', 'https://www.alfaparfmilano.com', 'luxury'),
  ('alpecin', 'Alpecin', 'https://alpecin.com', 'everyday'),
  ('and-honey', '&honey', 'https://andhoney.jp', 'everyday'),
  ('apothecare-essentials', 'ApotheCARE Essentials', 'https://www.apothecareessentials.com', 'everyday'),
  ('aquage', 'Aquage', 'https://www.aquage.com', 'luxury'),
  ('aquis', 'Aquis', 'https://aquis.com', 'luxury'),
  ('arimino', 'Arimino', 'https://www.arimino.co.jp', 'luxury'),
  ('asience', 'Kao Asience', 'https://www.kao.com/jp/asience', 'everyday'),
  ('authentic-beauty-concept', 'Authentic Beauty Concept', 'https://www.authenticbeautyconcept.com', 'luxury'),
  ('aveeno', 'Aveeno', 'https://www.aveeno.com', 'everyday'),
  ('bare-republic', 'Bare Republic', 'https://www.barerepublic.com', 'everyday'),
  ('bask-and-bloom', 'Bask & Bloom', 'https://www.baskandbloomessentials.com', 'everyday'),
  ('bekura-beauty', 'Bekura Beauty', 'https://bekurabeauty.com', 'luxury'),
  ('biolage', 'Biolage', 'https://www.biolage.com', 'luxury'),
  ('bobeam', 'Bobeam', 'https://www.bobeam.com', 'luxury'),
  ('botanist', 'Botanist', 'https://botanistofficial.com', 'everyday'),
  ('capillus', 'Capillus', 'https://www.capillus.com', 'luxury'),
  ('chi-haircare', 'CHI Haircare', 'https://chi.com', 'luxury'),
  ('cosrx', 'Cosrx', 'https://www.cosrx.com', 'everyday'),
  ('curl-junkie', 'Curl Junkie', 'https://www.curljunkie.com', 'everyday'),
  ('curlmix', 'CurlMix', 'https://www.curlmix.com', 'everyday'),
  ('curls', 'CURLS', 'https://www.curls.biz', 'everyday'),
  ('curls-dynasty', 'Curls Dynasty', 'https://www.curlsdynasty.com', 'everyday'),
  ('daeng-gi-meo-ri', 'Daeng Gi Meo Ri', 'https://www.daenggimeori.com', 'everyday'),
  ('designme', 'DesignME', 'https://designmehair.com', 'luxury'),
  ('donnas-recipe', 'Donna''s Recipe', 'https://www.donnasrecipe.com', 'everyday'),
  ('doux', 'Doux', 'https://thedoux.com', 'everyday'),
  ('etude-house', 'Etude House', 'https://www.etudehouse.com', 'everyday'),
  ('eucerin', 'Eucerin', 'https://www.eucerin.com', 'everyday'),
  ('eufora', 'Eufora', 'https://eufora.net', 'luxury'),
  ('evo-hair', 'evo hair', 'https://evohair.com', 'luxury'),
  ('fable-and-mane', 'Fable & Mane', 'https://www.fableandmane.com', 'luxury'),
  ('fanola', 'Fanola', 'https://www.fanola.com', 'luxury'),
  ('felicia-leatherwood', 'Felicia Leatherwood', 'https://www.felicialeatherwood.com', 'luxury'),
  ('folexin', 'Folexin', 'https://www.folexin.com', 'luxury'),
  ('foligain', 'Foligain', 'https://www.foligain.com', 'luxury'),
  ('framesi', 'Framesi', 'https://www.framesi.com', 'luxury'),
  ('function-of-beauty', 'Function of Beauty', 'https://www.functionofbeauty.com', 'luxury'),
  ('ghd', 'ghd', 'https://www.ghdhair.com', 'luxury'),
  ('goldwell', 'Goldwell', 'https://www.goldwell.com', 'luxury'),
  ('goongbe', 'Goongbe', 'https://goongbe.us', 'everyday'),
  ('gromd', 'GroMD', 'https://www.gromd.com', 'luxury'),
  ('hair-la-vie', 'Hair La Vie', 'https://hairlavie.com', 'luxury'),
  ('hair-rituel-sisley', 'Hair Rituel by Sisley', 'https://www.sisley-paris.com', 'luxury'),
  ('hairburst', 'Hairburst', 'https://www.hairburst.com', 'everyday'),
  ('hairfinity', 'Hairfinity', 'https://www.hairfinity.com', 'everyday'),
  ('hairitage', 'Hairitage by Mindy', 'https://www.hairitagebymindy.com', 'everyday'),
  ('hairlust', 'Hairlust', 'https://www.hairlust.com', 'luxury'),
  ('hairmax', 'Hairmax', 'https://www.hairmax.com', 'luxury'),
  ('hask-beauty', 'Hask Beauty', 'https://www.haskbeauty.com', 'everyday'),
  ('head-and-shoulders', 'Head & Shoulders', 'https://headandshoulders.com', 'everyday'),
  ('henna-sooq', 'Henna Sooq', 'https://www.hennasooq.com', 'everyday'),
  ('hers', 'Hers', 'https://www.forhers.com', 'luxury'),
  ('hims', 'Hims', 'https://www.forhims.com', 'luxury'),
  ('inahsi-naturals', 'Inahsi Naturals', 'https://www.inahsi.com', 'everyday'),
  ('indola', 'Indola', 'https://www.indola.com', 'luxury'),
  ('innate-life', 'Innate Life', 'https://theinnatelife.com', 'luxury'),
  ('irestore', 'iRestore', 'https://www.irestorelaser.com', 'luxury'),
  ('jakeala', 'Jakeala', 'https://www.jakeala.com', 'everyday'),
  ('just-nutritive', 'Just Nutritive', 'https://justnutritive.com', 'everyday'),
  ('jvn-hair', 'JVN Hair', 'https://jvnhair.com', 'luxury'),
  ('karens-body-beautiful', 'Karen''s Body Beautiful', 'https://karensbodybeautiful.com', 'everyday'),
  ('keeps', 'Keeps', 'https://www.keeps.com', 'luxury'),
  ('kemon', 'Kemon', 'https://www.kemon.com', 'luxury'),
  ('kreyol-essence', 'Kreyol Essence', 'https://www.kreyolessence.com', 'luxury'),
  ('kurlee-belle', 'Kurlee Belle', 'https://www.kurleebelle.com', 'everyday'),
  ('la-roche-posay', 'La Roche-Posay', 'https://www.laroche-posay.us', 'luxury'),
  ('lebel-cosmetics', 'Lebel Cosmetics', 'https://www.lebel.co.jp', 'luxury'),
  ('lipogaine', 'Lipogaine', 'https://lipogaine.com', 'everyday'),
  ('loma', 'Loma', 'https://www.lomaforhair.com', 'luxury'),
  ('lus-brands', 'Lus Brands', 'https://lusbrands.com', 'luxury'),
  ('mahogany-naturals', 'Mahogany Naturals', 'https://mahoganynaturals.com', 'everyday'),
  ('mane-n-tail', 'Mane ''n Tail', 'https://www.manentail.com', 'everyday'),
  ('maple-holistics', 'Maple Holistics', 'https://www.mapleholistics.com', 'everyday'),
  ('maria-nila', 'Maria Nila', 'https://marianila.com', 'luxury'),
  ('matrix', 'Matrix', 'https://www.matrix.com', 'luxury'),
  ('mise-en-scene', 'Mise en Scene', 'https://www.miseenscene.co.kr', 'everyday'),
  ('nashi-argan', 'Nashi Argan', 'https://www.nashiargan.com', 'luxury'),
  ('naturall-club', 'NaturAll Club', 'https://naturallclub.com', 'everyday'),
  ('neutrogena', 'Neutrogena T/Gel', 'https://www.neutrogena.com', 'everyday'),
  ('nizoral', 'Nizoral', 'https://www.nizoral.com', 'everyday'),
  ('number-76', 'Number 76', 'https://www.number76.com', 'luxury'),
  ('pacifica-beauty', 'Pacifica Beauty', 'https://www.pacificabeauty.com', 'everyday'),
  ('pacinos', 'Pacinos Signature Line', 'https://www.pacinos.com', 'everyday'),
  ('plantur-39', 'Plantur 39', 'https://www.plantur39.com', 'everyday'),
  ('pulp-riot', 'Pulp Riot', 'https://www.pulpriothair.com', 'luxury'),
  ('pyunkang-yul', 'Pyunkang Yul', 'https://pyunkangyul.com', 'luxury'),
  ('ranavat', 'Ranavat', 'https://www.ranavat.com', 'luxury'),
  ('revitalash', 'Revitalash', 'https://www.revitalash.com', 'luxury'),
  ('sam-villa', 'Sam Villa', 'https://samvilla.com', 'luxury'),
  ('saphira', 'Saphira', 'https://saphira.com', 'luxury'),
  ('scalpmed', 'ScalpMED', 'https://www.scalpmed.com', 'luxury'),
  ('schwarzkopf-professional', 'Schwarzkopf Professional', 'https://www.schwarzkopf-professional.com', 'luxury'),
  ('sebastian-professional', 'Sebastian Professional', 'https://www.sebastianprofessional.com', 'luxury'),
  ('selsun-blue', 'Selsun Blue', 'https://www.selsunblue.com', 'everyday'),
  ('shea-radiance', 'Shea Radiance', 'https://www.shearadiance.com', 'everyday'),
  ('show-beauty', 'Show Beauty', 'https://showbeauty.com', 'luxury'),
  ('skinfood', 'Skinfood', 'https://www.theskinfood.com', 'everyday'),
  ('sky-organics', 'Sky Organics', 'https://www.skyorganics.com', 'everyday'),
  ('sukin', 'Sukin', 'https://www.sukinnaturals.com', 'everyday'),
  ('sulwhasoo', 'Sulwhasoo', 'https://www.sulwhasoo.com', 'luxury'),
  ('sun-bum', 'Sun Bum', 'https://www.trustthebum.com', 'everyday'),
  ('suncoat', 'Suncoat', 'https://www.suncoatproducts.com', 'everyday'),
  ('surface-hair', 'Surface Hair', 'https://www.surfacehair.com', 'luxury'),
  ('system-professional', 'System Professional', 'https://www.systemprofessional.com', 'luxury'),
  ('t3-micro', 'T3 Micro', 'https://www.t3micro.com', 'luxury'),
  ('tabitha-james-kraan', 'Tabitha James Kraan', 'https://tabithajameskraan.com', 'luxury'),
  ('tangle-teezer', 'Tangle Teezer', 'https://www.tangleteezer.com', 'everyday'),
  ('the-inkey-list', 'The Inkey List', 'https://theinkeylist.com', 'everyday'),
  ('the-ordinary', 'The Ordinary', 'https://theordinary.com', 'everyday'),
  ('theradome', 'Theradome', 'https://www.theradome.com', 'luxury'),
  ('toppik', 'Toppik', 'https://www.toppik.com', 'everyday'),
  ('trepadora', 'Trepadora', 'https://trepadora.com', 'everyday'),
  ('tropic-isle-living', 'Tropic Isle Living', 'https://www.tropicisleliving.com', 'everyday'),
  ('tsubaki', 'Tsubaki', 'https://www.shiseido.co.jp/tsubaki', 'everyday'),
  ('vichy', 'Vichy', 'https://www.vichy.com', 'luxury'),
  ('viviscal', 'Viviscal', 'https://www.viviscal.com', 'luxury'),
  ('wahl-professional', 'Wahl Professional', 'https://www.wahlpro.com', 'everyday'),
  ('watermans', 'Watermans', 'https://watermanshair.com', 'everyday'),
  ('wellbel', 'Wellbel', 'https://wellbel.com', 'luxury'),
  ('wild-growth', 'Wild Growth', 'https://www.wildgrowthco.com', 'everyday'),
  ('wow-skin-science', 'Wow Skin Science', 'https://www.buywow.in', 'everyday')
on conflict (slug) do update set
  name        = excluded.name,
  website_url = excluded.website_url,
  tier        = coalesce(excluded.tier, brands.tier);
