-- Auto-generated by `scraper dump-schema`. Edit the Literal
-- in scraper/validation/models.py, then regenerate.

alter table public.ingredients drop constraint if exists ingredients_function_tags;
alter table public.ingredients add constraint ingredients_function_tags
  check (function_tags <@ array[
    'solvent',
    'humectant',
    'emollient',
    'occlusive',
    'fatty_alcohol',
    'drying_alcohol',
    'anionic_surfactant',
    'cationic_surfactant',
    'nonionic_surfactant',
    'amphoteric_surfactant',
    'silicone_water_soluble',
    'silicone_non_water_soluble',
    'silicone_volatile',
    'protein_hydrolyzed',
    'protein_intact',
    'plant_oil',
    'butter',
    'polyquat',
    'film_former',
    'preservative',
    'chelator',
    'ph_adjuster',
    'fragrance',
    'essential_oil',
    'exfoliant',
    'antioxidant',
    'ceramide',
    'heat_protectant',
    'uv_filter',
    'antidandruff',
    'other'
  ]::text[]);

