"""Render the SQL CHECK DDL from the Python enum state and verify the DB
agrees. `run-extraction` calls `check_db_drift` before any paid Firecrawl
work so a forgotten migration fails loudly rather than stranding credits.
"""

import re
from typing import get_args

import asyncpg

from .models import HairProductCategory, HairProductCurrency, HairProductSubcategory


# (constraint name, column name, Literal type) for each column backed by a
# closed taxonomy. Drives both DDL rendering and the drift check.
_CHECKS = (
    ("products_category_check", "category", HairProductCategory),
    ("products_subcategory_check", "subcategory", HairProductSubcategory),
    ("products_currency_check", "currency", HairProductCurrency),
)


def _render_check(constraint: str, column: str, values: tuple[str, ...]) -> str:
    indent = "    "
    vals = (",\n" + indent).join(f"'{v}'" for v in values)
    return (
        f"alter table products drop constraint if exists {constraint};\n"
        f"alter table products add constraint {constraint}\n"
        f"  check ({column} is null or {column} in (\n"
        f"{indent}{vals}\n"
        f"  ));"
    )


def render_migration() -> str:
    """Full DDL that drops + re-adds both CHECKs from the current Python source."""
    header = (
        "-- Auto-generated by `scraper dump-schema`. Edit `SUBCATEGORY_TO_CATEGORY`\n"
        "-- or the category Literal in scraper/validation/models.py, then regenerate.\n"
    )
    blocks = [_render_check(name, col, get_args(lit)) for name, col, lit in _CHECKS]
    return header + "\n" + "\n\n".join(blocks) + "\n"


_LITERAL_RE = re.compile(r"'([^']+)'")


async def _extract_values(conn: asyncpg.Connection, constraint: str) -> list[str]:
    row = await conn.fetchrow(
        "select pg_get_constraintdef(oid) as def from pg_constraint where conname = $1",
        constraint,
    )
    if row is None:
        raise RuntimeError(f"DB constraint {constraint!r} not found")
    return _LITERAL_RE.findall(row["def"])


async def check_db_drift(conn: asyncpg.Connection) -> None:
    """Raise RuntimeError if DB CHECK values differ from the Python enum state."""
    for constraint, _column, literal in _CHECKS:
        actual = set(await _extract_values(conn, constraint))
        expected = set(get_args(literal))
        missing_in_db = expected - actual
        missing_in_py = actual - expected
        if missing_in_db or missing_in_py:
            parts = []
            if missing_in_db:
                parts.append(f"missing in DB: {sorted(missing_in_db)}")
            if missing_in_py:
                parts.append(f"missing in Python: {sorted(missing_in_py)}")
            raise RuntimeError(
                f"schema drift on {constraint}: " + "; ".join(parts) + ". "
                "Run `uv run python -m scraper dump-schema` and apply the "
                "resulting migration."
            )
