"""Render the SQL CHECK DDL from the Python enum state and verify the DB
agrees. `run-extraction` calls `check_db_drift` before any paid Firecrawl
work; `tag-batch` does the same before any paid LLM work.
"""

import re
from typing import Literal, get_args

import asyncpg

from .models import (
    FunctionTag,
    HairProductCategory,
    HairProductCurrency,
    HairProductSubcategory,
)


# (constraint name, column name, Literal type) for each products column
# backed by a closed taxonomy. Drives both DDL rendering and the drift
# check.
_PRODUCT_CHECKS = (
    ("products_category_check", "category", HairProductCategory),
    ("products_subcategory_check", "subcategory", HairProductSubcategory),
    ("products_currency_check", "currency", HairProductCurrency),
)

# Single check for the ingredients.function_tags array column.
_INGREDIENT_CHECK = ("ingredients_function_tags", "function_tags", FunctionTag)


Target = Literal["products", "ingredients"]


def _render_product_check(constraint: str, column: str, values: tuple[str, ...]) -> str:
    indent = "    "
    vals = (",\n" + indent).join(f"'{v}'" for v in values)
    return (
        f"alter table products drop constraint if exists {constraint};\n"
        f"alter table products add constraint {constraint}\n"
        f"  check ({column} is null or {column} in (\n"
        f"{indent}{vals}\n"
        f"  ));"
    )


def _render_ingredient_check(constraint: str, column: str, values: tuple[str, ...]) -> str:
    indent = "    "
    vals = (",\n" + indent).join(f"'{v}'" for v in values)
    return (
        f"alter table public.ingredients drop constraint if exists {constraint};\n"
        f"alter table public.ingredients add constraint {constraint}\n"
        f"  check ({column} <@ array[\n"
        f"{indent}{vals}\n"
        f"  ]::text[]);"
    )


def render_migration(target: Target = "products") -> str:
    """Full DDL that drops + re-adds the CHECK(s) for `target` from the
    current Python source. Default `products` preserves the original
    behavior of `dump-schema` (no flag)."""
    header = (
        "-- Auto-generated by `scraper dump-schema`. Edit the Literal\n"
        "-- in scraper/validation/models.py, then regenerate.\n"
    )
    if target == "products":
        blocks = [
            _render_product_check(name, col, get_args(lit))
            for name, col, lit in _PRODUCT_CHECKS
        ]
    else:
        name, col, lit = _INGREDIENT_CHECK
        blocks = [_render_ingredient_check(name, col, get_args(lit))]
    return header + "\n" + "\n\n".join(blocks) + "\n"


_LITERAL_RE = re.compile(r"'([^']+)'")


async def _extract_values(conn: asyncpg.Connection, constraint: str) -> list[str]:
    row = await conn.fetchrow(
        "select pg_get_constraintdef(oid) as def from pg_constraint where conname = $1",
        constraint,
    )
    if row is None:
        raise RuntimeError(f"DB constraint {constraint!r} not found")
    return _LITERAL_RE.findall(row["def"])


async def check_db_drift(
    conn: asyncpg.Connection, target: Target = "products"
) -> None:
    """Raise RuntimeError if DB CHECK values differ from the Python enum
    state for the chosen `target`."""
    checks = _PRODUCT_CHECKS if target == "products" else (_INGREDIENT_CHECK,)
    for constraint, _column, literal in checks:
        actual = set(await _extract_values(conn, constraint))
        expected = set(get_args(literal))
        missing_in_db = expected - actual
        missing_in_py = actual - expected
        if missing_in_db or missing_in_py:
            parts = []
            if missing_in_db:
                parts.append(f"missing in DB: {sorted(missing_in_db)}")
            if missing_in_py:
                parts.append(f"missing in Python: {sorted(missing_in_py)}")
            raise RuntimeError(
                f"schema drift on {constraint}: " + "; ".join(parts) + ". "
                f"Run `uv run python -m scraper dump-schema --target {target}` "
                "and apply the resulting migration."
            )
